version: '3.9'
services:
  app-coverage:
    container_name: app-coverage
    image: app-coverage
    networks:
      - app-coverage
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  app-coverage: